version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: meditate-postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgesql/data

volumes:
  postgres:
    name: meditate-db